#
# MIT License
#
# Copyright (c) 2023 Gerald Venzl
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

name: Tests
on: [push, pull_request]

jobs:

  test-app-with-oracle-db:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 🛠  🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: 🔩 🐍 Install Python dependencies
        run: python -m pip install oracledb requests flask

      - name: 💻 Setup SQLcl
        uses: gvenzl/setup-oracle-sqlcl@v1

      - name: ⭕ Setup test database
        uses: gvenzl/setup-oracle-free@v1
        with:
          tag: slim
          app-user: gerald
          app-user-password: LetsHaveFun1

      - name: 🚀 Deploy changes
        run: |
          cd src/demo/database
          echo "lb update -changelog-file changelog.xml" | \
          sql gerald/LetsHaveFun1@${{ secrets.DB_HOST }}/${{ secrets.DB_NAME }} 

      - name: 🔬 Run test
        run: |
          export APP_USER=gerald
          export APP_USER_PASSWORD=LetsHaveFun1
          export PYTHONPATH=$PWD
          cd src/demo
          flask --app main run &
          sleep 3
          cd ../test
          python test.py
