name: DOAG

on: [push, pull_request]

jobs:

  test-data-load:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
    - name: ⭕ Setup test database
        uses: gvenzl/setup-oracle-free@v1
        with:
          tag: slim
          app-user: gerald
          app-user-password: LetsHaveFun1
          
     - name: 💻 Setup SQLcl
        uses: gvenzl/setup-oracle-sqlcl@v1
    
    - name: Install data set
      run: |
          wget https://raw.githubusercontent.com/gvenzl/sample-data/refs/heads/main/countries-cities-currencies/install.sql
          sql gerald/LetsHaveFun1@localhost/freepdb1 @install.sql

